title:         'Practical'
description:   'A practical template/theme for personal blogging.'
baseurl:       '/practical' # do not end with /
url:           'https://itsuhane.github.io' # do not end with /

author:
  name:        'itsuhane'
  email:       'some@email.here'

permalink:     pretty

paginate:      2
paginate_path: '/blog/page-:num/'

markdown:      kramdown

gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-sass-converter
