# Settings for site and template

title:         'Practical'
description:   'A practical template/theme for personal blogging. Inspired by Hyde, Hydejack and jekyll-doc-theme.'
baseurl:       '/practical' # do not end with /
url:           'https://itsuhane.github.io' # do not end with /

author:
  name:        'itsuhane'
  email:       'some@email.here'

repository:    'itsuhane/practical'

features:
  latex:       katex
  fontawesome: true
  compress:    true

# Settings for Jekyll and GitHub Pages

encoding:      utf-8

markdown:      kramdown

permalink:     pretty

paginate:      10
paginate_path: '/blog/page-:num/'

gems:
  - jemoji
#  - jekyll-sitemap
#  - jekyll-feed
  - jekyll-sass-converter

#sass:
#  style: compressed

defaults:
  - scope:
      path: "/blog/"
    values:
      layout: "post"
source: '_source'
